<?
include('local.conf.php');
$langnames = array(
  'bg' => 'Bulgarian',
  'cs' => 'Czech',
  'da' => 'Danish',
  'de' => 'German',
  'en' => 'English',
  'en-rUS' => 'English (US) - Please translate only non common strings!',
  'el' => 'Greek',
  'es' => 'Spanish',
  'fr' => 'French',
  'hr' => 'Croatian',
  'hu' => 'Hungarian',
  'it' => 'Italian',
  'iw' => 'Hebrew',
  'ko' => 'Korean',
  'nb' => 'Norwegian',
  'nl' => 'Dutch',
  'pl' => 'Polish',
  'pt' => 'Poruguese',
  'pt-rBR' => 'Poruguese (Brasil) - Please translate only non common strings!',
  'ro' => 'Romanian',
  'ru' => 'Russian',
  'sk' => 'Slovak',
  'sv' => 'Swedish',
  'tr' => 'Turkish',
  'uk' => 'Ukrainian',
  'zh' => 'Chinese',
 );
?>
